### ISSUE TITLE
The repo owner is drunk on power

### ISSUE THREAD

**Issue by dlinch** [bradford-hamilton/deriks-profile-page#2]
I had a legitimate issue opened on this project and the repo owner closed it surreptitiously; I can only assume because he's a big meanie-face.

**Comment by dlinch** [comment]
@bradford-hamilton I think this issue needs your attention

**Comment by bradford-hamilton** [comment]
Oh hey there @dlinch, I believe your request was to take the app down. I responded letting you know that this is an open source project! If that's what you'd like to see - feel free to open a PR! Thanks Derik.
